# Generated by Django 6.0.4 on 2026-05-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number_provided',
            field=models.BooleanField(default=False),
        ),
    ]
